version: "3.7"
networks:
  demo-net:
services:
  spark:
    image: star/all-spark-notebook-thrift:latest
    ports:
    - "8888:8888/tcp"
    - "4040:4040/tcp"
    - "10000:10000/tcp"
    networks:
    - demo-net
    working_dir: /home/$USER/work
    environment:
      CHOWN_HOME: "yes"
      GRANT_SUDO: "yes"
      NB_UID: 1000
      NB_GID: 100
      NB_USER: $USER
      NB_GROUP: staff
    user: root
    deploy:
     replicas: 1
     restart_policy:
       condition: on-failure
    volumes:
    - $PWD/work:/home/$USER/work
    - $PWD/conf/hive-site.xml:/usr/local/spark/conf/hive-site.xml
    depends_on:
      - postgres
  postgres:
    image: postgres:9.6.17-alpine
    ports:
    - 5432:5432
    networks:
    - demo-net
    volumes:
      - ./hive-metastore/:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=metastore
  adminer:
    image: adminer:latest
    ports:
    - "8080:8080/tcp"
    networks:
    - demo-net
    deploy:
     restart_policy:
       condition: on-failure
  # dbt:
  #   image: star/dbt-all:latest
  #   entrypoint: /bin/bash
  #   networks:
  #   - demo-net
  #   volumes:
  #     - $PWD/dbt-app:/usr/app 
  #     - $PWD/dbt-app/profiles.yml:/root/.dbt/profiles.yml