spark_demo:
  outputs:
    dev:
      host: localhost
      method: thrift
      port: 10000
      schema: spark_demo
      threads: 1
      type: spark
      user: postgres
      password: postgres
      dbname: spark_demo
  target: dev
